version: '3'

services:
  rails:
    build:
      context: .
      dockerfile: Docker_rails
    command: /bin/sh -c "cd app && rm -f /app/tmp/pids/server.pid && bundle install && bundle exec rails s -b 0.0.0.0"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 3000:3000
    
  react:
    build:
      context: .
      dockerfile: Docker_react
    command: /bin/sh -c "cd frontend && yarn && yarn start"
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/frontend
    ports:
      - 4000:3000